### ISSUE TITLE
Coverage and node_modules directories not in gitignore

### ISSUE THREAD

**Issue by eliasmalik** [olot/wordpanda#17]
Is there a reason your coverage and node_modules directories are committed instead of ignored?

**Comment by JackTierney** [comment]
@eliascodes hey man, we sorted that out, it is a bit of a bitch if it has already been pushed, you have deleted them from your local completely. Adding them to the .gitignore then re-pushing doesn't work!  Delete from local - push/pull - put back and stuff in a .gitignore, re-push.

Of course sticking it in a .gitignore from the get go avoids this altogether! :dart:

**Comment by eliasmalik** [comment]
Yeah for node_modules and coverage, it's not such a big deal if they exist in your git history, because its not a security issue, it's just annoying for anyone cloning your repo to have to download more than necessary. Obviously much more important for api keys, passwords, server config info, etc.
